import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.107.0/+esm'

const SUPABASE_URL = 'https://vzxxpsbpsqifpdejirxx.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_MM0stuYzn60rnZstXHJpgQ_bIBZUuPD'
const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: false } })
const app = document.querySelector('#app')

const rounds = [
  { no:1, event:'ดอกเบี้ยตลาดเพิ่มขึ้น', rate:'5% → 7%', correct:'down', label:'Discount Bond', explanation:'พันธบัตรเดิมให้ Coupon 5% แต่ตลาดให้ 7% จึงน่าสนใจน้อยลง ราคาต้องลดลงเพื่อให้ผลตอบแทนแข่งขันได้' },
  { no:2, event:'ดอกเบี้ยตลาดลดลง', rate:'5% → 3%', correct:'up', label:'Premium Bond', explanation:'พันธบัตรเดิมให้ Coupon 5% สูงกว่าตลาดที่ 3% นักลงทุนจึงยอมจ่ายแพงขึ้น' },
  { no:3, event:'ดอกเบี้ยตลาดไม่เปลี่ยน', rate:'5% = 5%', correct:'par', label:'Par Bond', explanation:'เมื่อ Market Rate เท่ากับ Coupon Rate ราคาพันธบัตรจะอยู่ใกล้ Par Value 1,000 บาท' },
  { no:4, event:'ข่าวเงินเฟ้อทำให้ดอกเบี้ยตลาดสูงขึ้น', rate:'5% → 6%', correct:'down', label:'Discount Bond', explanation:'อัตราผลตอบแทนที่ตลาดต้องการสูงขึ้น ราคาพันธบัตรเดิมจึงลดลง' },
  { no:5, event:'ตลาดคาดว่าธนาคารกลางจะลดดอกเบี้ย', rate:'5% → 4%', correct:'up', label:'Premium Bond', explanation:'เมื่อดอกเบี้ยตลาดลดลง Coupon 5% ของพันธบัตรเดิมดูน่าสนใจขึ้น ราคาจึงเพิ่มขึ้น' },
]
const answerLabels = { up:'ราคาพันธบัตร ↑', down:'ราคาพันธบัตร ↓', par:'ราคา ≈ 1,000 บาท' }
let hostSession = null, playerSession = null, currentChannel = null, pollId = null

function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pct(n,d){return d ? Math.round((n/d)*1000)/10 : 0}
function shell(content){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">BP</span><span>Bond Pulse</span></div><span class="badge">15 นาที • Bond Valuation</span></header>${content}<footer class="footer">Bond Pulse • Classroom learning game</footer></div>`}
function friendly(error){const m=error?.message||'';if(m.includes('ROOM_NOT_FOUND'))return'ไม่พบห้องนี้ หรือเกมจบแล้ว';if(m.includes('NICKNAME_TAKEN'))return'ชื่อนี้มีคนใช้แล้ว กรุณาใช้ชื่ออื่น';if(m.includes('INVALID_NICKNAME'))return'กรุณาใส่ชื่อเล่น 1–24 ตัวอักษร';if(m.includes('ROUND_CLOSED'))return'รอบนี้ปิดรับคำตอบแล้ว';if(m.includes('AUTHORISED'))return'สิทธิ์เข้าห้องไม่ถูกต้อง กรุณาเข้าห้องใหม่';return'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง'}
function bondCard(){return `<div class="bond-card"><div><span>Par Value</span><b>1,000 บาท</b></div><div><span>Coupon Rate</span><b>5%</b></div><div><span>อายุคงเหลือ</span><b>5 ปี</b></div></div>`}
function stopSync(){if(pollId){clearInterval(pollId);pollId=null}if(currentChannel){supabase.removeChannel(currentChannel);currentChannel=null}}
function startSync(code, callback){stopSync();currentChannel=supabase.channel(`bond-pulse:${code}`,{config:{broadcast:{self:true}}}).on('broadcast',{event:'room_update'},callback).subscribe();pollId=setInterval(callback,2500)}
async function ping(code){const ch=currentChannel||supabase.channel(`bond-pulse:${code}`);try{await ch.send({type:'broadcast',event:'room_update',payload:{at:Date.now()}})}catch{}}

function landing(){stopSync();location.hash='';shell(`<section class="hero"><div><span class="badge">สำหรับผู้เริ่มต้น • ไม่ต้องลงทะเบียน</span><h1>Bond Pulse</h1><p>เกม 15 นาทีที่ช่วยให้นักศึกษาเข้าใจความสัมพันธ์ที่สำคัญที่สุดของ Bond Valuation ก่อนเรียนสูตรคำนวณ</p><div class="concept"><span>ดอกเบี้ยตลาด ↑ → ราคาพันธบัตร ↓</span><span>ดอกเบี้ยตลาด ↓ → ราคาพันธบัตร ↑</span></div></div><div class="panel menu"><button class="primary" id="hostBtn">หน้าจอผู้สอน (Instructor)</button><button class="secondary" id="joinBtn">เข้าร่วมเกม (Student)</button><div class="small">ผู้เรียนใช้เพียง Room Code + ชื่อเล่น ไม่มีบัญชี ไม่มี leaderboard และไม่คิดคะแนนจากความเร็ว</div></div></section>`);document.querySelector('#hostBtn').onclick=()=>hostSetup();document.querySelector('#joinBtn').onclick=()=>studentJoin()}

function hostSetup(){location.hash='host';shell(`<section class="panel center"><button class="back" id="back">← กลับ</button><h1>เริ่มห้องเรียนใหม่</h1><p>สร้าง Room Code แล้วให้นักศึกษาเข้าผ่านโทรศัพท์ได้ทันที</p><button class="primary" id="create">สร้างห้อง (Create Room)</button><div id="err"></div></section>`);document.querySelector('#back').onclick=landing;document.querySelector('#create').onclick=createRoom}
async function createRoom(){const btn=document.querySelector('#create');btn.disabled=true;btn.textContent='กำลังสร้างห้อง…';const {data,error}=await supabase.rpc('bp_create_room');if(error){document.querySelector('#err').innerHTML=`<div class="error">${friendly(error)}</div>`;btn.disabled=false;btn.textContent='สร้างห้อง (Create Room)';return}const r=data?.[0];hostSession={roomId:r.room_id,code:r.room_code,hostToken:r.host_token};sessionStorage.setItem('bp_host',JSON.stringify(hostSession));startSync(hostSession.code,refreshHost);await refreshHost();await ping(hostSession.code)}
async function refreshHost(){if(!hostSession)return;const {data,error}=await supabase.rpc('bp_host_state',{p_room_id:hostSession.roomId,p_host_token:hostSession.hostToken});if(error){shell(`<div class="panel center"><div class="error">${friendly(error)}</div><button class="secondary" id="backHome">กลับหน้าแรก</button></div>`);document.querySelector('#backHome').onclick=landing;return}renderHost(data)}
function renderHost(s){if(s.status==='finished'){renderFinal(s);return}if(s.status==='lobby'){const players=(s.players||[]).map(p=>`<span class="player-chip">${esc(p.nickname)}</span>`).join('');shell(`<div class="host-grid"><section class="panel"><div class="round-head"><span class="badge">Lobby</span><span class="badge">นักศึกษา ${s.participantCount} คน</span></div><div class="join-note">ให้นักศึกษาเข้า Bond Pulse แล้วใส่ Room Code</div><div class="room-code">${s.code}</div><div class="player-list">${players||'<span class="hint">กำลังรอนักศึกษาเข้าร่วม…</span>'}</div><div class="actions"><button class="primary" id="start" ${s.participantCount<1?'disabled':''}>เริ่มเกม</button><button class="secondary" id="end">จบห้อง</button></div></section><aside class="panel timing"><h3>แผน 15 นาที</h3><div class="timing-step"><span>Intro</span><strong>3 นาที</strong></div><div class="timing-step"><span>Game 5 รอบ</span><strong>8 นาที</strong></div><div class="timing-step"><span>Debrief</span><strong>4 นาที</strong></div><p class="small">ไม่บังคับเวลาอัตโนมัติ ผู้สอนควบคุมจังหวะเอง</p></aside></div>`);document.querySelector('#start').onclick=()=>hostAction('start');document.querySelector('#end').onclick=()=>hostAction('end');return}
const r=rounds[s.currentRound-1];const dist=s.currentDistribution||{up:0,down:0,par:0};const correctPct=pct(s.currentCorrect,s.currentAnswered);shell(`<div class="host-grid"><section class="panel"><div class="round-head"><span class="round-no">รอบ ${r.no} / 5</span><span class="badge">ตอบแล้ว ${s.currentAnswered} / ${s.participantCount}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct(s.currentAnswered,s.participantCount)}%"></div></div><div class="scenario"><h2>${r.event}</h2><div class="rate">${r.rate}</div></div>${bondCard()}<h3>คำตอบของชั้นเรียน</h3><div class="distribution">${['up','down','par'].map(k=>`<div class="dist-row"><span>${answerLabels[k]}</span><div class="bar-track"><div class="bar-fill" style="width:${pct(dist[k]||0,s.currentAnswered)}%"></div></div><strong>${dist[k]||0}</strong></div>`).join('')}</div>${s.revealed?`<div class="reveal"><strong>คำตอบ: ${answerLabels[r.correct]} • ${r.label}</strong><div>${r.explanation}</div><div>ตอบถูก ${correctPct}%</div></div>`:''}<div class="actions">${s.revealed?`<button class="primary" id="next">${r.no===5?'สรุปผล':'รอบถัดไป →'}</button>`:`<button class="primary" id="reveal">เฉลยรอบนี้</button>`}<button class="secondary" id="end">จบเกม</button></div></section><aside class="panel"><h3>Live participation</h3><div class="stat-row"><div class="stat"><strong>${s.participantCount}</strong>เข้าร่วม</div><div class="stat"><strong>${s.currentAnswered}</strong>ตอบรอบนี้</div><div class="stat"><strong>${s.overallAccuracy}%</strong>Overall</div></div><div class="small">คะแนนเน้นความเข้าใจ ไม่คิดความเร็ว</div></aside></div>`);if(document.querySelector('#reveal'))document.querySelector('#reveal').onclick=()=>hostAction('reveal');if(document.querySelector('#next'))document.querySelector('#next').onclick=()=>hostAction('next');document.querySelector('#end').onclick=()=>hostAction('end')}
async function hostAction(action){const {error}=await supabase.rpc('bp_host_action',{p_room_id:hostSession.roomId,p_host_token:hostSession.hostToken,p_action:action});if(error){alert(friendly(error));return}await ping(hostSession.code);await refreshHost()}
function renderFinal(s){const ra=s.roundAccuracy||[];const eligible=ra.filter(x=>Number(x.answered)>0);const worst=eligible.slice().sort((a,b)=>Number(a.accuracy)-Number(b.accuracy))[0];const partial=Math.max(0,Number(s.participantCount)-Number(s.completedAll));shell(`<section class="panel"><h1>สรุปผลทั้งห้อง</h1><p>Debrief 4 นาที</p><div class="stat-row"><div class="stat"><strong>${s.participantCount}</strong>เข้าร่วม</div><div class="stat"><strong>${s.completedAll}</strong>เล่นครบ 5 รอบ</div><div class="stat"><strong>${partial}</strong>เข้าร่วมบางส่วน</div></div><div class="stat-row"><div class="stat"><strong>${s.overallAccuracy}%</strong>Overall Accuracy</div></div><h3>Accuracy รายรอบ</h3><div class="round-bars">${ra.map(x=>`<div class="round-bar"><span>R${x.round}</span><div class="bar-track"><div class="bar-fill" style="width:${x.accuracy}%"></div></div><strong>${x.accuracy}%</strong></div>`).join('')}</div>${worst?`<p>รอบที่ควรทบทวนมากที่สุด: <strong>รอบ ${worst.round}</strong> (${worst.accuracy}% ตอบถูก)</p>`:''}<div class="takeaway">จำเพียงประโยคเดียว: ดอกเบี้ยตลาด ↑ → ราคาพันธบัตร ↓ &nbsp; | &nbsp; ดอกเบี้ยตลาด ↓ → ราคาพันธบัตร ↑</div><div class="debrief"><strong>คำถามสรุป</strong><p>1. ทำไมพันธบัตรเดิมที่จ่าย 5% จึงน่าสนใจน้อยลงเมื่อพันธบัตรใหม่ให้ 7%?</p><p>2. ถ้าคาดว่าดอกเบี้ยตลาดกำลังจะลดลง คุณอยากถือพันธบัตรเดิมหรือไม่ เพราะอะไร?</p></div><div class="actions"><button class="primary" id="newRoom">สร้างห้องใหม่</button></div></section>`);document.querySelector('#newRoom').onclick=()=>{sessionStorage.removeItem('bp_host');hostSession=null;hostSetup()}}

function studentJoin(){location.hash='join';shell(`<section class="panel center"><button class="back" id="back">← กลับ</button><h1>เข้าร่วม Bond Pulse</h1><form id="joinForm"><div class="field"><label for="code">Room Code</label><input class="code-input" id="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="123456" required></div><div class="field"><label for="nickname">ชื่อเล่น</label><input id="nickname" maxlength="24" placeholder="เช่น Mint" required></div><div id="err"></div><button class="primary" style="width:100%" type="submit">เข้าร่วมเกม</button></form></section>`);document.querySelector('#back').onclick=landing;document.querySelector('#code').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,6));document.querySelector('#joinForm').onsubmit=joinRoom}
async function joinRoom(e){e.preventDefault();const code=document.querySelector('#code').value.trim(),nickname=document.querySelector('#nickname').value.trim();const {data,error}=await supabase.rpc('bp_join_room',{p_code:code,p_nickname:nickname});if(error){document.querySelector('#err').innerHTML=`<div class="error">${friendly(error)}</div>`;return}const r=data?.[0];playerSession={roomId:r.room_id,code:r.room_code,playerId:r.player_id,playerToken:r.player_token,nickname};sessionStorage.setItem('bp_player',JSON.stringify(playerSession));startSync(code,refreshPlayer);await refreshPlayer();await ping(code)}
async function refreshPlayer(){if(!playerSession)return;const [rr,pr]=await Promise.all([supabase.rpc('bp_room_state',{p_code:playerSession.code}),supabase.rpc('bp_player_state',{p_room_id:playerSession.roomId,p_player_id:playerSession.playerId,p_player_token:playerSession.playerToken})]);if(rr.error||pr.error){shell(`<div class="panel center"><div class="error">${friendly(rr.error||pr.error)}</div><button class="secondary" id="backHome">กลับหน้าแรก</button></div>`);document.querySelector('#backHome').onclick=landing;return}renderPlayer(rr.data,pr.data)}
function renderPlayer(room,player){if(room.status==='lobby'){shell(`<section class="panel center" style="text-align:center"><span class="badge">Room ${playerSession.code}</span><h1>เข้าร่วมแล้ว</h1><p><strong>${esc(playerSession.nickname)}</strong> รอผู้สอนเริ่มเกม</p><div class="stat"><strong>${room.participantCount}</strong>คนในห้อง</div></section>`);return}if(room.status==='finished'){shell(`<section class="panel center" style="text-align:center"><h1>จบเกมแล้ว</h1><div class="score">${player.score}<span>/5</span></div><p>คะแนนของคุณ</p><div class="takeaway">ดอกเบี้ยตลาด ↑ → ราคาพันธบัตร ↓<br>ดอกเบี้ยตลาด ↓ → ราคาพันธบัตร ↑</div></section>`);return}const r=rounds[room.currentRound-1];const answered=Boolean(player.currentAnswer);shell(`<section class="panel"><div class="student-top"><span>Room ${playerSession.code}</span><strong>${esc(playerSession.nickname)}</strong><span>คะแนน ${player.score}/${room.revealed?room.currentRound:Math.max(0,room.currentRound-1)}</span></div><div class="round-head"><span class="round-no">รอบ ${r.no} / 5</span></div><div class="scenario" style="text-align:center"><h2>${r.event}</h2><div class="rate">${r.rate}</div></div>${bondCard()}<h2 style="text-align:center">ราคาพันธบัตรเดิมจะเป็นอย่างไร?</h2><div class="answers">${['up','down','par'].map(k=>`<button class="answer ${player.currentAnswer===k?'selected':''}" data-answer="${k}" ${answered||room.revealed?'disabled':''}>${answerLabels[k]}</button>`).join('')}</div>${answered&&!room.revealed?'<div class="submitted">ส่งคำตอบแล้ว รอผู้สอนเฉลย</div>':''}${room.revealed?`<div class="student-reveal ${player.currentCorrect?'correct':'wrong'}"><strong>${player.currentCorrect?'✓ ถูกต้อง':'ยังไม่ถูก'}</strong><p>คำตอบ: ${answerLabels[r.correct]} • ${r.label}</p><div>${r.explanation}</div><p><strong>คะแนนสะสม ${player.score}/${room.currentRound}</strong></p></div>`:''}</section>`);document.querySelectorAll('[data-answer]').forEach(btn=>btn.onclick=()=>submitAnswer(btn.dataset.answer,room.currentRound))}
async function submitAnswer(answer,roundNo){document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);const {error}=await supabase.rpc('bp_submit_answer',{p_room_id:playerSession.roomId,p_player_id:playerSession.playerId,p_player_token:playerSession.playerToken,p_round:roundNo,p_answer:answer});if(error){alert(friendly(error));await refreshPlayer();return}await ping(playerSession.code);await refreshPlayer()}

function resume(){try{const h=sessionStorage.getItem('bp_host');const p=sessionStorage.getItem('bp_player');if(location.hash==='#host'&&h){hostSession=JSON.parse(h);startSync(hostSession.code,refreshHost);refreshHost();return}if(location.hash==='#join'&&p){playerSession=JSON.parse(p);startSync(playerSession.code,refreshPlayer);refreshPlayer();return}}catch{}if(location.hash==='#host')hostSetup();else if(location.hash==='#join')studentJoin();else landing()}
window.addEventListener('hashchange',()=>{if(location.hash==='#host'&&!hostSession)hostSetup();else if(location.hash==='#join'&&!playerSession)studentJoin();else if(!location.hash)landing()})
resume()
